version: '3.8'

services:
  react-app:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    command: sh -c "npm install && npm run build && npm install -g serve && serve -s build -l 3005"
